# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 933432347888d3780c24cb66ed0320b152a1eaa5731979a6b792143c45705b20052422787585c587ace725f7301a56f278651c9ac849dd05b485819089754253

test:
  secret_key_base: ee38468d953336b52152204ea02cba15bf4beddb384dd382908dbfe16349c003afc52a137222e8d01020602235573db5d18d4eeebd27fb50924bd48f40137a64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
